Checks if site secure, uses wss if not uses ws
praekeltfoundation/momkhulu pull request #22
Opened 2018-08-03 16:33 UTC by nyashabryan

I had forgotten to consider that if the site is using https instead of HTTP,  there is a connection using the wss:// instead of ws://. I changed the JS so that it checks if the current configuration it is using is secure or it isn't, then decides to whether to use secure sockets or not.

2018-08-13 07:43 UTC, nathanbegbie commented
@nyashabryan I think we might want to default to only using `https`, given the nature of the data that we are sending over the sockets. We can set up the site so that anyone requesting `http` is redirected to `https`.

So I think in this case we can set up the JS to only use `wss`

2018-08-13 08:34 UTC, nathanbegbie requested changes
@nyashabryan I think we might want to default to only using `https`, given the nature of the data that we are sending over the sockets. We can set up the site so that anyone requesting `http` is redirected to `https`.

So I think in this case we can set up the JS to only use `wss`

2018-08-24 22:18 UTC, nyashabryan commented
@nathanbegbie I understand what you mean. Changing the Websocket to be fixed on ws// means that the wss// will be not be supported locally in the testing environment.. That is why I had chosen to support both.

2018-08-29 06:31 UTC, nathanbegbie commented
@nyashabryan hmmmm . . . that's a good point. Okay, we clearly don't want to hinder a developer if they want to get started, but we also want to avoid a case where production data is served in an unsecured manner. What do you think about the following as a solution . . .
Allow what you're currently suggesting, BUT include a banner that is displayed when served over `http` AND `DEBUG==False` warning the user that they should check the setup.

2018-09-03 19:45 UTC, nyashabryan commented
@nathanbegbie I am thinking about using the `SecurityMiddleware` to redirect all the non-https traffic to https using the `SECURE_SSL_REDIRECT = True` in production settings. This will redirect all the HTTP traffic to HTTPS. I looked at Lebombo and I didn't see that set, so I am guessing maybe the redirects are set on the serving infrastructure, Gunicorn/Nginx? I think this might help make sure that if we are running on production settings, the application will only serve https.

2018-09-03 19:48 UTC, nyashabryan commented
@nathanbegbie I am thinking about using the `SecurityMiddleware` to redirect all the non-https traffic to https using the `SECURE_SSL_REDIRECT = True` in production settings. This will redirect all the HTTP traffic to HTTPS. I looked at Lebombo and I didn't see that set, so I am guessing maybe the redirects are set on the serving infrastructure, Gunicorn/Nginx? I think this might help make sure that if we are running on production settings, the application will only serve https.

2018-09-04 06:44 UTC, nathanbegbie commented
@nyasha You're correct, the way we set up automatic redirects to https is set with Nginx, as a conifguration that we pass in to our deployment infrastructure. So don't worry about setting that up within Django.

2019-04-08 07:11 UTC, closed without merging